<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <?php echo $this->tag->getTitle(); ?>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <?php
  $this->assets->outputCss("headerCss");
  $this->assets->outputJs("headerJs");
  ?>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <b>Admin</b>LTE
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">登录开始您的会话</p>

    <form action="<?php echo $this->url->get('public/login')?>" method="post">
        <?php echo $this->getContent(); ?>
      <div class="form-group has-feedback">
        <?php echo $form->render('account');?>
        <?php echo $form->get('account')->getUserOption('icon');?>
      </div>
      <div class="form-group has-feedback">
        <?php echo $form->render('password');?>
        <?php echo $form->get('password')->getUserOption('icon');?>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <div class="form-group has-feedback">
          <?php echo $form->render('captcha');?>
          <?php echo $form->get('captcha')->getUserOption('icon');?>
          </div>
        </div>
        <div class="col-xs-6">
          <img alt="点击换图" id="codeImg" style="cursor:pointer; width:100px;height: 40px;" src="/admin/public/captcha" align="absmiddle">
        </div>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <!-- <div class="checkbox icheck">
            <label>
              <input type="checkbox"> 记住我
            </label>
          </div> -->
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <!-- <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
    </div> -->
    <!-- /.social-auth-links -->

    <a href="#">忘记密码请联系管理员</a><br>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<?php $this->assets->outputJs("footerJs");?>
<script>
  $(function () {
    //切换验证码
    $("#codeImg").click(function () {
      $(this).attr('src', '/admin/public/captcha?=' + Math.random(0,1));
    });
  });
</script>
</body>
</html>

