<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">用户列表</h3>
                    <div class="margin">
                        <!-- 加载编辑器的容器 -->
                        <script id="container" name="content" type="text/plain">
                            这里写你的初始化内容
                        </script>
                        <button type="input" id="upload_btn" name="upload_btn" value="">上传图片</button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
<?php //echo $this->tag->ueditor('container','full'); ?>
<?php echo $this->tag->ueditor('upload','images'); ?>
</script>